#ifndef ROS_TIM_PRV_H
#define ROS_TIM_PRV_H

/****************************************************************************************************
*                                                                                     ▄▄▄,/,
*   ROS_tim_prv.h                                                                   ▄▀  ,/▄ 
*                                                                                  ▐▌ ,/' ▐▌
*   Defines RoveOS timer private functions.                                        /▀/'  ▄▀ 
*                                                                                  └' ▀▀▀   
****************************************************************************************************/

/****************************************************************************************************
*   Includes
****************************************************************************************************/
/*  Public   */
#include "ROS_tim_pub.h"
/*  Private  */

/****************************************************************************************************
*   Macros
****************************************************************************************************/
#define NONE_TIM_CHANNEL 0xFFFF
#define NONE_AF_PORT 0xFFFF
#define NONE_TIM {NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}

/****************************************************************************************************
*   Types
****************************************************************************************************/

/****************************************************************************************************
*   Variables
****************************************************************************************************/
static const TIMChannel NONE_TIM_CHANNEL_STRUCT = {NONE_TIM_CHANNEL, NONE_AF_PORT, NULL};

static const PinDef pindefs[] =
{
	{GPIOA, GPIO_PIN_0, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_1, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_1, {{TIM_CHANNEL_2, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_2, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_2, {{TIM_CHANNEL_3, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_3, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_3, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_4, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_4, NONE_TIM},
	{GPIOA, GPIO_PIN_5, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_8, {{TIM_CHANNEL_1, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_9, {{TIM_CHANNEL_2, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_10, {{TIM_CHANNEL_3, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_11, {{TIM_CHANNEL_4, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_12, NONE_TIM},
	{GPIOA, GPIO_PIN_13, NONE_TIM},
	{GPIOA, GPIO_PIN_14, NONE_TIM},
	{GPIOA, GPIO_PIN_15, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},

	{GPIOB, GPIO_PIN_0, {{TIM_CHANNEL_3, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_1, {{TIM_CHANNEL_4, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_2, NONE_TIM},
	{GPIOB, GPIO_PIN_3, {{TIM_CHANNEL_2, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_4, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_5, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_8, {{TIM_CHANNEL_1, GPIO_AF1_TIM16, TIM16}, {TIM_CHANNEL_3, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_9, {{TIM_CHANNEL_1, GPIO_AF1_TIM17, TIM17}, {TIM_CHANNEL_4, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_10, {{TIM_CHANNEL_3, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_11, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_12, NONE_TIM},
	{GPIOB, GPIO_PIN_13, NONE_TIM},
	{GPIOB, GPIO_PIN_14, {{TIM_CHANNEL_1, GPIO_AF2_TIM12, TIM12}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_15, {{TIM_CHANNEL_2, GPIO_AF2_TIM12, TIM12}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},

	{GPIOC, GPIO_PIN_0, NONE_TIM},
	{GPIOC, GPIO_PIN_1, NONE_TIM},
	{GPIOC, GPIO_PIN_2, {{TIM_CHANNEL_1, GPIO_AF1_TIM17, TIM17}, {TIM_CHANNEL_4, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_3, NONE_TIM},
	{GPIOC, GPIO_PIN_4, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_5, NONE_TIM},
	{GPIOC, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_1, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_2, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_8, {{TIM_CHANNEL_3, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_3, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_9, {{TIM_CHANNEL_4, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_4, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_10, NONE_TIM},
	{GPIOC, GPIO_PIN_11, NONE_TIM},
	{GPIOC, GPIO_PIN_12, {{TIM_CHANNEL_1, GPIO_AF2_TIM15, TIM15}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_13, NONE_TIM},
	{GPIOC, GPIO_PIN_14, NONE_TIM},
	{GPIOC, GPIO_PIN_15, NONE_TIM},

	{GPIOD, GPIO_PIN_0, NONE_TIM},
	{GPIOD, GPIO_PIN_1, NONE_TIM},
	{GPIOD, GPIO_PIN_2, NONE_TIM},
	{GPIOD, GPIO_PIN_3, NONE_TIM},
	{GPIOD, GPIO_PIN_4, NONE_TIM},
	{GPIOD, GPIO_PIN_5, NONE_TIM},
	{GPIOD, GPIO_PIN_6, NONE_TIM},
	{GPIOD, GPIO_PIN_7, NONE_TIM},
	{GPIOD, GPIO_PIN_8, NONE_TIM},
	{GPIOD, GPIO_PIN_9, NONE_TIM},
	{GPIOD, GPIO_PIN_10, NONE_TIM},
	{GPIOD, GPIO_PIN_11, NONE_TIM},
	{GPIOD, GPIO_PIN_12, {{TIM_CHANNEL_1, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_13, {{TIM_CHANNEL_2, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_14, {{TIM_CHANNEL_3, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_15, {{TIM_CHANNEL_4, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},

	{GPIOE, GPIO_PIN_0, NONE_TIM},
	{GPIOE, GPIO_PIN_1, NONE_TIM},
	{GPIOE, GPIO_PIN_2, NONE_TIM},
	{GPIOE, GPIO_PIN_3, NONE_TIM},
	{GPIOE, GPIO_PIN_4, NONE_TIM},
	{GPIOE, GPIO_PIN_5, {{TIM_CHANNEL_1, GPIO_AF4_TIM15, TIM15}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_6, {{TIM_CHANNEL_2, GPIO_AF4_TIM15, TIM15}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_7, NONE_TIM},
	{GPIOE, GPIO_PIN_8, NONE_TIM},
	{GPIOE, GPIO_PIN_9, {{TIM_CHANNEL_1, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_10, NONE_TIM},
	{GPIOE, GPIO_PIN_11, {{TIM_CHANNEL_2, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_12, NONE_TIM},
	{GPIOE, GPIO_PIN_13, {{TIM_CHANNEL_3, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_14, {{TIM_CHANNEL_4, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_15, NONE_TIM},

	{GPIOF, GPIO_PIN_0, NONE_TIM},
	{GPIOF, GPIO_PIN_1, NONE_TIM},
	{GPIOF, GPIO_PIN_2, NONE_TIM},
	{GPIOF, GPIO_PIN_3, NONE_TIM},
	{GPIOF, GPIO_PIN_4, NONE_TIM},
	{GPIOF, GPIO_PIN_5, NONE_TIM},
	{GPIOF, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF1_TIM16, TIM16}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOF, GPIO_PIN_7, {{TIM_CHANNEL_1, GPIO_AF1_TIM17, TIM17}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOF, GPIO_PIN_8, NONE_TIM},
	{GPIOF, GPIO_PIN_9, NONE_TIM},
	{GPIOF, GPIO_PIN_10, NONE_TIM},
	{GPIOF, GPIO_PIN_11, NONE_TIM},
	{GPIOF, GPIO_PIN_12, NONE_TIM},
	{GPIOF, GPIO_PIN_13, NONE_TIM},
	{GPIOF, GPIO_PIN_14, NONE_TIM},
	{GPIOF, GPIO_PIN_15, NONE_TIM},

	{GPIOG, GPIO_PIN_0, NONE_TIM},
	{GPIOG, GPIO_PIN_1, NONE_TIM},
	{GPIOG, GPIO_PIN_2, NONE_TIM},
	{GPIOG, GPIO_PIN_3, NONE_TIM},
	{GPIOG, GPIO_PIN_4, NONE_TIM},
	{GPIOG, GPIO_PIN_5, NONE_TIM},
	{GPIOG, GPIO_PIN_6, NONE_TIM},
	{GPIOG, GPIO_PIN_7, NONE_TIM},
	{GPIOG, GPIO_PIN_8, NONE_TIM},
	{GPIOG, GPIO_PIN_9, NONE_TIM},
	{GPIOG, GPIO_PIN_10, NONE_TIM},
	{GPIOG, GPIO_PIN_11, NONE_TIM},
	{GPIOG, GPIO_PIN_12, NONE_TIM},
	{GPIOG, GPIO_PIN_13, NONE_TIM},
	{GPIOG, GPIO_PIN_14, NONE_TIM},
	{GPIOG, GPIO_PIN_15, NONE_TIM},

	{GPIOH, GPIO_PIN_0, NONE_TIM},
	{GPIOH, GPIO_PIN_1, NONE_TIM},
	{GPIOH, GPIO_PIN_2, NONE_TIM},
	{GPIOH, GPIO_PIN_3, NONE_TIM},
	{GPIOH, GPIO_PIN_4, NONE_TIM},
	{GPIOH, GPIO_PIN_5, NONE_TIM},
	{GPIOH, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM12, TIM12}, {TIM_CHANNEL_1, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_7, {{TIM_CHANNEL_3, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_8, {{TIM_CHANNEL_2, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_9, {{TIM_CHANNEL_2, GPIO_AF1_TIM1, TIM1}, {TIM_CHANNEL_2, GPIO_AF2_TIM12, TIM12}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_10, {{TIM_CHANNEL_1, GPIO_AF2_TIM5, TIM5}, {TIM_CHANNEL_3, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_11, {{TIM_CHANNEL_3, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOH, GPIO_PIN_12, NONE_TIM},
	{GPIOH, GPIO_PIN_13, NONE_TIM},
	{GPIOH, GPIO_PIN_14, NONE_TIM},
	{GPIOH, GPIO_PIN_15, NONE_TIM},

	{GPIOI, GPIO_PIN_0, {{TIM_CHANNEL_4, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOI, GPIO_PIN_1, NONE_TIM},
	{GPIOI, GPIO_PIN_2, {{TIM_CHANNEL_4, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOI, GPIO_PIN_3, NONE_TIM},
	{GPIOI, GPIO_PIN_4, NONE_TIM},
	{GPIOI, GPIO_PIN_5, {{TIM_CHANNEL_1, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOI, GPIO_PIN_6, {{TIM_CHANNEL_2, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOI, GPIO_PIN_7, {{TIM_CHANNEL_3, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOI, GPIO_PIN_8, NONE_TIM},
	{GPIOI, GPIO_PIN_9, NONE_TIM},
	{GPIOI, GPIO_PIN_10, NONE_TIM},
	{GPIOI, GPIO_PIN_11, NONE_TIM},
};

/****************************************************************************************************
*   Private Functions
****************************************************************************************************/
void initPWMPin(Pin pin, uint64_t range, uint64_t freq, TIM_HandleTypeDef* htim, uint16_t* returnChannel);
uint64_t getAPBTimerSpeed(TIM_TypeDef* tim);
void initTIM(uint64_t prescaler, uint64_t period, TIM_TypeDef* tim, TIM_HandleTypeDef* htim);

#endif /* ROS_TIM_PRV_H */