#ifndef ROVE_OS
#define ROVE_OS


#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stddef.h>
#include <stdbool.h>
#include "stm32f4xx_hal.h"

//TODO: break these out into seperate module files when there is further project definition.

//Add more AF definitions here.
typedef struct {
	uint16_t channel;
	uint16_t AFPort;
	TIM_TypeDef* tim;
} TIMChannel;

typedef struct {
	GPIO_TypeDef* GPIOPort;
	uint16_t GPIOPin;
	TIMChannel timChannels[3];
} PinDef;

#define NONE_TIM_CHANNEL 0xFFFFFFFF
#define NONE_AF_PORT 0xFFFFFFFF
static const TIMChannel NONE_TIM_CHANNEL_STRUCT = {NONE_TIM_CHANNEL, NONE_AF_PORT, NULL};
#define NONE_TIM {NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}

typedef enum
{
	PA0,PA1,PA2,PA3,PA4,PA5,PA6,PA7,PA8,PA9,PA10,PA11,PA12,PA13,PA14,PA15,
	PB0,PB1,PB2,PB3,PB4,PB5,PB6,PB7,PB8,PB9,PB10,PB11,PB12,PB13,PB14,PB15,
	PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,
	PD0,PD1,PD2,PD3,PD4,PD5,PD6,PD7,PD8,PD9,PD10,PD11,PD12,PD13,PD14,PD15,
	PE0,PE1,PE2,PE3,PE4,PE5,PE6,PE7,PE8,PE9,PE10,PE11,PE12,PE13,PE14,PE15,
	PF0,PF1,PF2,PF3,PF4,PF5,PF6,PF7,PF8,PF9,PF10,PF11,PF12,PF13,PF14,PF15,
	PG0,PG1,PG2,PG3,PG4,PG5,PG6,PG7,PG8,PG9,PG10,PG11,PG12,PG13,PG14,PG15,
	PH0,PH1,PH2,PH3,PH4,PH5,PH6,PH7,PH8,PH9,PH10,PH11,PH12,PH13,PH14,PH15,
	PI0,PI1,PI2,PI3,PI4,PI5,PI6,PI7,PI8,PI9,PI10,PI11,
} Pin;

static const PinDef pindefs[] =
{
	{GPIOA, GPIO_PIN_0, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_1, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_1, {{TIM_CHANNEL_2, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_2, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_2, {{TIM_CHANNEL_3, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_3, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_3, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, {TIM_CHANNEL_4, GPIO_AF2_TIM5, TIM5}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_4, NONE_TIM},
	{GPIOA, GPIO_PIN_5, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_8, {{TIM_CHANNEL_1, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_9, {{TIM_CHANNEL_2, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_10, {{TIM_CHANNEL_3, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_11, {{TIM_CHANNEL_4, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOA, GPIO_PIN_12, NONE_TIM},
	{GPIOA, GPIO_PIN_13, NONE_TIM},
	{GPIOA, GPIO_PIN_14, NONE_TIM},
	{GPIOA, GPIO_PIN_15, {{TIM_CHANNEL_1, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},

	{GPIOB, GPIO_PIN_0, {{TIM_CHANNEL_3, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_1, {{TIM_CHANNEL_4, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_2, NONE_TIM},
	{GPIOB, GPIO_PIN_3, {{TIM_CHANNEL_2, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_4, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_5, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_8, NONE_TIM},
	{GPIOB, GPIO_PIN_9, NONE_TIM},
	{GPIOB, GPIO_PIN_10, {{TIM_CHANNEL_3, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_11, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOB, GPIO_PIN_12, NONE_TIM},
	{GPIOB, GPIO_PIN_13, NONE_TIM},
	{GPIOB, GPIO_PIN_14, NONE_TIM},
	{GPIOB, GPIO_PIN_15, NONE_TIM},

	{GPIOC, GPIO_PIN_0, NONE_TIM},
	{GPIOC, GPIO_PIN_1, NONE_TIM},
	{GPIOC, GPIO_PIN_2, NONE_TIM},
	{GPIOC, GPIO_PIN_3, NONE_TIM},
	{GPIOC, GPIO_PIN_4, {{TIM_CHANNEL_4, GPIO_AF1_TIM2, TIM2}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_5, NONE_TIM},
	{GPIOC, GPIO_PIN_6, {{TIM_CHANNEL_1, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_1, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_7, {{TIM_CHANNEL_2, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_2, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_8, {{TIM_CHANNEL_3, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_3, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_9, {{TIM_CHANNEL_4, GPIO_AF2_TIM3, TIM3}, {TIM_CHANNEL_4, GPIO_AF3_TIM8, TIM8}, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOC, GPIO_PIN_10, NONE_TIM},
	{GPIOC, GPIO_PIN_11, NONE_TIM},
	{GPIOC, GPIO_PIN_12, NONE_TIM},
	{GPIOC, GPIO_PIN_13, NONE_TIM},
	{GPIOC, GPIO_PIN_14, NONE_TIM},
	{GPIOC, GPIO_PIN_15, NONE_TIM},

	{GPIOD, GPIO_PIN_0, NONE_TIM},
	{GPIOD, GPIO_PIN_1, NONE_TIM},
	{GPIOD, GPIO_PIN_2, NONE_TIM},
	{GPIOD, GPIO_PIN_3, NONE_TIM},
	{GPIOD, GPIO_PIN_4, NONE_TIM},
	{GPIOD, GPIO_PIN_5, NONE_TIM},
	{GPIOD, GPIO_PIN_6, NONE_TIM},
	{GPIOD, GPIO_PIN_7, NONE_TIM},
	{GPIOD, GPIO_PIN_8, NONE_TIM},
	{GPIOD, GPIO_PIN_9, NONE_TIM},
	{GPIOD, GPIO_PIN_10, NONE_TIM},
	{GPIOD, GPIO_PIN_11, NONE_TIM},
	{GPIOD, GPIO_PIN_12, {{TIM_CHANNEL_1, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_13, {{TIM_CHANNEL_2, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_14, {{TIM_CHANNEL_3, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOD, GPIO_PIN_15, {{TIM_CHANNEL_4, GPIO_AF2_TIM4, TIM4}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},

	{GPIOE, GPIO_PIN_0, NONE_TIM},
	{GPIOE, GPIO_PIN_1, NONE_TIM},
	{GPIOE, GPIO_PIN_2, NONE_TIM},
	{GPIOE, GPIO_PIN_3, NONE_TIM},
	{GPIOE, GPIO_PIN_4, NONE_TIM},
	{GPIOE, GPIO_PIN_5, NONE_TIM},
	{GPIOE, GPIO_PIN_6, NONE_TIM},
	{GPIOE, GPIO_PIN_7, NONE_TIM},
	{GPIOE, GPIO_PIN_8, NONE_TIM},
	{GPIOE, GPIO_PIN_9, {{TIM_CHANNEL_1, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_10, NONE_TIM},
	{GPIOE, GPIO_PIN_11, {{TIM_CHANNEL_2, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_12, NONE_TIM},
	{GPIOE, GPIO_PIN_13, {{TIM_CHANNEL_3, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_14, {{TIM_CHANNEL_4, GPIO_AF1_TIM1, TIM1}, NONE_TIM_CHANNEL_STRUCT, NONE_TIM_CHANNEL_STRUCT}},
	{GPIOE, GPIO_PIN_15, NONE_TIM},

	{GPIOF, GPIO_PIN_0, NONE_TIM},
	{GPIOF, GPIO_PIN_1, NONE_TIM},
	{GPIOF, GPIO_PIN_2, NONE_TIM},
	{GPIOF, GPIO_PIN_3, NONE_TIM},
	{GPIOF, GPIO_PIN_4, NONE_TIM},
	{GPIOF, GPIO_PIN_5, NONE_TIM},
	{GPIOF, GPIO_PIN_6, NONE_TIM},
	{GPIOF, GPIO_PIN_7, NONE_TIM},
	{GPIOF, GPIO_PIN_8, NONE_TIM},
	{GPIOF, GPIO_PIN_9, NONE_TIM},
	{GPIOF, GPIO_PIN_10, NONE_TIM},
	{GPIOF, GPIO_PIN_11, NONE_TIM},
	{GPIOF, GPIO_PIN_12, NONE_TIM},
	{GPIOF, GPIO_PIN_13, NONE_TIM},
	{GPIOF, GPIO_PIN_14, NONE_TIM},
	{GPIOF, GPIO_PIN_15, NONE_TIM},

	{GPIOG, GPIO_PIN_0, NONE_TIM},
	{GPIOG, GPIO_PIN_1, NONE_TIM},
	{GPIOG, GPIO_PIN_2, NONE_TIM},
	{GPIOG, GPIO_PIN_3, NONE_TIM},
	{GPIOG, GPIO_PIN_4, NONE_TIM},
	{GPIOG, GPIO_PIN_5, NONE_TIM},
	{GPIOG, GPIO_PIN_6, NONE_TIM},
	{GPIOG, GPIO_PIN_7, NONE_TIM},
	{GPIOG, GPIO_PIN_8, NONE_TIM},
	{GPIOG, GPIO_PIN_9, NONE_TIM},
	{GPIOG, GPIO_PIN_10, NONE_TIM},
	{GPIOG, GPIO_PIN_11, NONE_TIM},
	{GPIOG, GPIO_PIN_12, NONE_TIM},
	{GPIOG, GPIO_PIN_13, NONE_TIM},
	{GPIOG, GPIO_PIN_14, NONE_TIM},
	{GPIOG, GPIO_PIN_15, NONE_TIM},
};

void initPWMPin(Pin pin, uint64_t range, uint64_t freq, TIM_HandleTypeDef* htim, uint16_t* returnChannel);

uint64_t getAPBTimerSpeed(TIM_TypeDef* tim);

void initTIM(uint64_t prescaler, uint64_t period, TIM_TypeDef* tim, TIM_HandleTypeDef* htim);


#ifdef __cplusplus
}
#endif


#endif
