################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/acd.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c \
C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c 

OBJS += \
./Middlewares/LwIP/Core/IPV4/acd.o \
./Middlewares/LwIP/Core/IPV4/autoip.o \
./Middlewares/LwIP/Core/IPV4/dhcp.o \
./Middlewares/LwIP/Core/IPV4/etharp.o \
./Middlewares/LwIP/Core/IPV4/icmp.o \
./Middlewares/LwIP/Core/IPV4/igmp.o \
./Middlewares/LwIP/Core/IPV4/ip4.o \
./Middlewares/LwIP/Core/IPV4/ip4_addr.o \
./Middlewares/LwIP/Core/IPV4/ip4_frag.o 

C_DEPS += \
./Middlewares/LwIP/Core/IPV4/acd.d \
./Middlewares/LwIP/Core/IPV4/autoip.d \
./Middlewares/LwIP/Core/IPV4/dhcp.d \
./Middlewares/LwIP/Core/IPV4/etharp.d \
./Middlewares/LwIP/Core/IPV4/icmp.d \
./Middlewares/LwIP/Core/IPV4/igmp.d \
./Middlewares/LwIP/Core/IPV4/ip4.d \
./Middlewares/LwIP/Core/IPV4/ip4_addr.d \
./Middlewares/LwIP/Core/IPV4/ip4_frag.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/LwIP/Core/IPV4/acd.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/acd.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/autoip.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/dhcp.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/etharp.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/icmp.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/igmp.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/ip4.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/ip4_addr.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/LwIP/Core/IPV4/ip4_frag.o: C:/Users/fanta/OneDrive/Documents/GitHub/stm32h5-classic-coremw-apps/Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c Middlewares/LwIP/Core/IPV4/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32H563xx -DUSE_FULL_LL_DRIVER -DUSE_STM32H5XX_NUCLEO -c -I../../Core/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32H5xx_HAL_Driver/Inc/Legacy -I../../../../../../../Drivers/CMSIS/Device/ST/STM32H5xx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../Drivers/BSP/STM32H5xx_Nucleo -I../../../../../../../Drivers/BSP/Components/Common -I../../../../../../../Drivers/BSP/Components/lan8742 -I../../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../../LWIP/App -I../../LWIP/Target -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-LwIP-2f-Core-2f-IPV4

clean-Middlewares-2f-LwIP-2f-Core-2f-IPV4:
	-$(RM) ./Middlewares/LwIP/Core/IPV4/acd.cyclo ./Middlewares/LwIP/Core/IPV4/acd.d ./Middlewares/LwIP/Core/IPV4/acd.o ./Middlewares/LwIP/Core/IPV4/acd.su ./Middlewares/LwIP/Core/IPV4/autoip.cyclo ./Middlewares/LwIP/Core/IPV4/autoip.d ./Middlewares/LwIP/Core/IPV4/autoip.o ./Middlewares/LwIP/Core/IPV4/autoip.su ./Middlewares/LwIP/Core/IPV4/dhcp.cyclo ./Middlewares/LwIP/Core/IPV4/dhcp.d ./Middlewares/LwIP/Core/IPV4/dhcp.o ./Middlewares/LwIP/Core/IPV4/dhcp.su ./Middlewares/LwIP/Core/IPV4/etharp.cyclo ./Middlewares/LwIP/Core/IPV4/etharp.d ./Middlewares/LwIP/Core/IPV4/etharp.o ./Middlewares/LwIP/Core/IPV4/etharp.su ./Middlewares/LwIP/Core/IPV4/icmp.cyclo ./Middlewares/LwIP/Core/IPV4/icmp.d ./Middlewares/LwIP/Core/IPV4/icmp.o ./Middlewares/LwIP/Core/IPV4/icmp.su ./Middlewares/LwIP/Core/IPV4/igmp.cyclo ./Middlewares/LwIP/Core/IPV4/igmp.d ./Middlewares/LwIP/Core/IPV4/igmp.o ./Middlewares/LwIP/Core/IPV4/igmp.su ./Middlewares/LwIP/Core/IPV4/ip4.cyclo ./Middlewares/LwIP/Core/IPV4/ip4.d ./Middlewares/LwIP/Core/IPV4/ip4.o ./Middlewares/LwIP/Core/IPV4/ip4.su ./Middlewares/LwIP/Core/IPV4/ip4_addr.cyclo ./Middlewares/LwIP/Core/IPV4/ip4_addr.d ./Middlewares/LwIP/Core/IPV4/ip4_addr.o ./Middlewares/LwIP/Core/IPV4/ip4_addr.su ./Middlewares/LwIP/Core/IPV4/ip4_frag.cyclo ./Middlewares/LwIP/Core/IPV4/ip4_frag.d ./Middlewares/LwIP/Core/IPV4/ip4_frag.o ./Middlewares/LwIP/Core/IPV4/ip4_frag.su

.PHONY: clean-Middlewares-2f-LwIP-2f-Core-2f-IPV4

